- hosts: 18.224.90.173
  tasks:
  - name: configure S3 on client instance
    copy:
      src: /etc/ansible/s3config.py
      dest: /home/ec2-user/

  - name: execute copied python file
    command: python3 ./s3config.py

